#!/usr/bin/env python3
"""atl-confluence: Confluence CLI with local HTML cache + version-aware push.

核心设计：
  - Confluence 页面以 storage XHTML 形式缓存到 <project-cwd>/.atlassian-cache/confluence/<page-id>/
  - 每个版本一个文件 v<N>.html；编辑草稿 v<N>.draft.html；元数据 .meta.json
  - push 前强校验远程版本号未变（防覆盖）
  - .atlassian-cache/.gitignore 自动写入，不污染仓库

子命令：
  pull <page-id> [--version N] [--force]    拉取页面到缓存
  push <page-id> [--force] [--draft FILE]   推送 draft 到远程（版本+1）
  diff <page-id>                            cached remote vs draft
  cache-status [--page-id ID]               列缓存状态
  clear-cache [--page-id ID]                清缓存
  get-page <page-id> [--format storage|markdown|view]   读单页
  create-page --space K --title T --parent P --file F   新建页面
  search --cql 'CQL'                        CQL 搜索
  get-page-children <page-id>               列子页
  get-page-history <page-id>                版本历史
  get-page-diff <page-id> --from V1 --to V2 远程版本 diff
  get-comments <page-id>                    列评论
  add-comment <page-id> --text TEXT         加评论
  delete-page <page-id>                     删页
  move-page <page-id> --parent NEW_PARENT   移动
  upload-attachment <page-id> --file F      上传附件
  download-attachment <page-id> --filename F [--out PATH]   下载附件

凭据/配置走 atl-query.ps1（PowerShell 必备）。本脚本用 subprocess 调用之。
"""

from __future__ import annotations

import argparse
import datetime as dt
import difflib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

CACHE_DIR_NAME = ".atlassian-cache"
GITIGNORE_CONTENT = "# Auto-generated by atlassian skill. Do not commit cache contents.\n*\n"


# ====== atl-query.ps1 wrapper ======


def _find_atl_query() -> str:
    """Locate atl-query.ps1 (same dir as this script)."""
    here = Path(__file__).resolve().parent
    p = here / "atl-query.ps1"
    if not p.exists():
        raise SystemExit(f"atl-query.ps1 not found next to {__file__}")
    return str(p)


def _ps_escape(s: str) -> str:
    """Escape single quotes for PowerShell single-quoted strings (double them)."""
    return s.replace("'", "''")


def call_api(
    service: str,
    path: str,
    *,
    method: str = "GET",
    body: str | None = None,
    body_file: str | None = None,
    content_type: str = "application/json",
) -> tuple[int, str, str]:
    """Call atl-query.ps1; return (return_code, stdout_text, stderr_text).

    PowerShell -Command does not proxy subprocess stdin into the script's pipeline,
    so any non-empty `body` is materialized to a UTF-8 temp file and sent via -BodyFile.
    """
    atl_query = _find_atl_query()
    cleanup_path: str | None = None
    if body and not body_file:
        tmp = tempfile.NamedTemporaryFile(suffix=".json", mode="w", encoding="utf-8", delete=False)
        try:
            tmp.write(body)
            tmp.close()
            body_file = tmp.name
            cleanup_path = tmp.name
        except Exception:
            tmp.close()
            os.unlink(tmp.name)
            raise

    cmd = (
        f"& '{_ps_escape(atl_query)}' -Service {service} -Path '{_ps_escape(path)}' -Method {method}"
        + (f" -ContentType '{_ps_escape(content_type)}'" if content_type != "application/json" else "")
        + (f" -BodyFile '{_ps_escape(body_file)}'" if body_file else "")
    )
    try:
        proc = subprocess.run(
            ["powershell", "-ExecutionPolicy", "Bypass", "-NoProfile", "-Command", cmd],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
        )
        return proc.returncode, proc.stdout or "", proc.stderr or ""
    finally:
        if cleanup_path:
            try:
                os.unlink(cleanup_path)
            except OSError:
                pass


def call_api_json(service: str, path: str, **kw) -> Any:
    """Call API and parse JSON response. Strips BOM if present."""
    rc, stdout, stderr = call_api(service, path, **kw)
    if rc != 0:
        raise SystemExit(f"API call failed (exit {rc}): {stderr}\n{stdout}")
    text = stdout.strip()
    if text.startswith("﻿"):
        text = text[1:]
    if not text:
        return None
    try:
        return json.loads(text)
    except json.JSONDecodeError as e:
        raise SystemExit(f"Failed to parse JSON response: {e}\nRaw: {text[:500]}")


# ====== Cache management ======


def atomic_write_text(path: Path, content: str, encoding: str = "utf-8") -> None:
    """Atomically write text to a file: write to .tmp sibling, then os.replace.
    Avoids partial files on crash / SIGINT mid-write."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + f".tmp.{os.getpid()}")
    try:
        tmp.write_text(content, encoding=encoding)
        os.replace(tmp, path)
    except Exception:
        if tmp.exists():
            try:
                tmp.unlink()
            except OSError:
                pass
        raise


class ConflictError(RuntimeError):
    """Raised when a Confluence PUT receives HTTP 409 (version conflict)."""


def get_cache_root(custom: str | None = None) -> Path:
    """Resolve cache root. Priority: --cache-dir > $ATL_CACHE_DIR > config.env CACHE_DIR > <cwd>/.atlassian-cache"""
    if custom:
        return Path(custom).resolve()

    env_override = os.environ.get("ATL_CACHE_DIR")
    if env_override:
        return Path(env_override).resolve()

    # Read config.env CACHE_DIR if present
    cfg = Path.home() / ".claude" / "skill-config" / "atlassian" / "config.env"
    if cfg.exists():
        for line in cfg.read_text(encoding="utf-8", errors="replace").splitlines():
            m = re.match(r"^CACHE_DIR=(.+)$", line)
            if m:
                return Path(m.group(1).strip()).resolve()

    return Path.cwd() / CACHE_DIR_NAME


def ensure_cache_dir(cache_root: Path, page_id: str) -> Path:
    """Create cache dir + .gitignore if missing. Return per-page cache dir."""
    cache_root.mkdir(parents=True, exist_ok=True)
    gi = cache_root / ".gitignore"
    if not gi.exists():
        gi.write_text(GITIGNORE_CONTENT, encoding="utf-8")
    page_dir = cache_root / "confluence" / page_id
    page_dir.mkdir(parents=True, exist_ok=True)
    return page_dir


def now_iso() -> str:
    return dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def get_agent_id() -> str:
    """Heuristic agent id from env."""
    for k in ("CLAUDE_CODE", "CLAUDE_AGENT", "CODEX_SESSION"):
        if os.environ.get(k):
            return k.lower().replace("_", "-")
    return os.environ.get("USERNAME") or os.environ.get("USER") or "unknown"


def read_meta(page_dir: Path) -> dict:
    meta_file = page_dir / ".meta.json"
    if not meta_file.exists():
        return {}
    try:
        return json.loads(meta_file.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}


def write_meta(page_dir: Path, meta: dict) -> None:
    (page_dir / ".meta.json").write_text(
        json.dumps(meta, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )


def append_push_log(page_dir: Path, line: str) -> None:
    log = page_dir / "push.log"
    with open(log, "a", encoding="utf-8") as f:
        f.write(f"{now_iso()} {line}\n")


# ====== Subcommand: pull ======


def cmd_pull(args: argparse.Namespace) -> int:
    cache_root = get_cache_root(args.cache_dir)
    page_dir = ensure_cache_dir(cache_root, args.page_id)

    # Build query: optionally request specific version via /history endpoint
    if args.version is not None:
        # Confluence Server: /rest/experimental/content/<id>/version/<n>
        # Server falls back to current via /rest/api/content/<id>?version=N - which doesn't actually filter
        # Use /rest/api/content/<id>/history to find versionId, then download via /rest/api/content/<id>?version=N
        path = f"rest/api/content/{args.page_id}?expand=body.storage,version,space,title&version={args.version}"
    else:
        path = f"rest/api/content/{args.page_id}?expand=body.storage,version,space,title"

    print(f"Fetching page {args.page_id}...", file=sys.stderr)
    data = call_api_json("confluence", path)
    if not data:
        raise SystemExit("Empty response from Confluence")

    version = data.get("version", {}).get("number")
    title = data.get("title", "")
    space_key = data.get("space", {}).get("key", "")
    body = (data.get("body", {}).get("storage", {}) or {}).get("value", "")

    if version is None:
        raise SystemExit(f"Missing version in response: {json.dumps(data)[:500]}")

    target = page_dir / f"v{version}.html"
    if target.exists() and not args.force:
        existing = target.read_text(encoding="utf-8")
        if existing == body:
            print(f"OK v{version} already cached (unchanged): {target}", file=sys.stderr)
        else:
            # Local file differs from remote v<N>. Common cause: previous pull was
            # interrupted leaving a partial write, or someone hand-edited v<N>.html
            # (which they shouldn't — base files are immutable, edit .draft.html instead).
            print(f"WARN v{version} cached but content differs from remote.", file=sys.stderr)
            print(f"     Local file may be partial/corrupt. Use --force to overwrite,", file=sys.stderr)
            print(f"     or rename it aside first (e.g. mv v{version}.html v{version}.local-edit.html).", file=sys.stderr)
            return 1
    else:
        atomic_write_text(target, body)
        print(f"OK fetched v{version} -> {target} ({len(body)} chars)", file=sys.stderr)

    # Create draft copy if not exists
    draft = page_dir / f"v{version}.draft.html"
    if not draft.exists():
        shutil.copy2(target, draft)
        print(f"OK draft created: {draft}", file=sys.stderr)
    else:
        print(f"INFO draft already exists (kept): {draft}", file=sys.stderr)

    # Update meta
    meta = read_meta(page_dir)
    meta.update({
        "page_id": args.page_id,
        "title": title,
        "space_key": space_key,
        "latest_remote_version": version,
        "latest_local_file": target.name,
        "fetched_at": now_iso(),
        "fetched_by_agent": get_agent_id(),
    })
    write_meta(page_dir, meta)

    print(f"\nNext: edit {draft.name}, then 'atl-confluence diff {args.page_id}' before push.")
    return 0


# ====== Subcommand: push ======


def cmd_push(args: argparse.Namespace) -> int:
    cache_root = get_cache_root(args.cache_dir)
    page_dir = cache_root / "confluence" / args.page_id

    if not page_dir.exists():
        raise SystemExit(f"No cache for page {args.page_id}. Run 'pull' first.")

    meta = read_meta(page_dir)
    cached_ver = meta.get("latest_remote_version")
    if not cached_ver:
        raise SystemExit(f"Cache meta missing latest_remote_version. Run 'pull --force' first.")

    # Determine draft file
    if args.draft:
        draft = Path(args.draft).resolve()
        if not draft.exists():
            raise SystemExit(f"Draft file not found: {draft}")
    else:
        draft = page_dir / f"v{cached_ver}.draft.html"
        if not draft.exists():
            raise SystemExit(
                f"No draft file at {draft}. "
                f"Either edit it manually after 'pull', or pass --draft <path>."
            )

    body = draft.read_text(encoding="utf-8")
    if not body.strip():
        raise SystemExit(f"Draft is empty: {draft}")

    # Re-verify remote version
    print(f"Verifying remote version (cached: v{cached_ver})...", file=sys.stderr)
    remote = call_api_json("confluence", f"rest/api/content/{args.page_id}?expand=version,title,space")
    remote_ver = remote.get("version", {}).get("number")
    title = remote.get("title", meta.get("title", ""))

    if remote_ver != cached_ver:
        if not args.force:
            print(
                f"\nERROR: remote at v{remote_ver}, your cache at v{cached_ver}.\n"
                f"Your draft is based on outdated version.\n"
                f"Options:\n"
                f"  1. atl-confluence pull {args.page_id} --force          # discard local, refetch latest\n"
                f"  2. atl-confluence pull {args.page_id} --version {remote_ver}  # add remote latest to cache, then merge manually\n"
                f"  3. atl-confluence push {args.page_id} --force          # force push (will overwrite remote v{remote_ver})\n",
                file=sys.stderr,
            )
            return 2
        else:
            print(f"WARN --force: pushing over remote v{remote_ver}", file=sys.stderr)

    new_version = remote_ver + 1
    payload = {
        "version": {"number": new_version},
        "title": title,
        "type": "page",
        "body": {
            "storage": {
                "value": body,
                "representation": "storage",
            }
        },
    }

    # Write payload to temp file, send via --data-binary @file
    tmp = tempfile.NamedTemporaryFile(suffix=".json", mode="w", encoding="utf-8", delete=False)
    try:
        json.dump(payload, tmp, ensure_ascii=False)
        tmp.close()

        print(f"PUT v{cached_ver} -> v{new_version}...", file=sys.stderr)
        rc, stdout, stderr = call_api(
            "confluence",
            f"rest/api/content/{args.page_id}",
            method="PUT",
            body_file=tmp.name,
        )
        if rc != 0:
            # Detect HTTP 409 (version conflict) and surface a structured message.
            # atl-query.ps1 emits "HTTP 409" via Write-Error so it lands in stderr.
            if "HTTP 409" in stderr:
                print(
                    f"\nERROR: Confluence rejected push with HTTP 409 (version conflict).\n"
                    f"Someone changed page {args.page_id} between your version check (v{remote_ver}) "
                    f"and the actual PUT.\n"
                    f"Recovery:\n"
                    f"  1. atl-confluence pull {args.page_id} --force   # discard local, refetch latest\n"
                    f"     (if you need to keep your edits, rename v{cached_ver}.draft.html aside first)\n"
                    f"  2. Re-apply your edits on top of the new version\n"
                    f"  3. atl-confluence push {args.page_id}\n",
                    file=sys.stderr,
                )
                if stdout:
                    print(f"Server response: {stdout[:500]}", file=sys.stderr)
                return 3
            # Other error
            print(f"ERROR push failed: {stderr}", file=sys.stderr)
            print(stdout[:1000], file=sys.stderr)
            return 1
    finally:
        os.unlink(tmp.name)

    # On success: persist as v<new>.html (atomic), drop draft, update meta
    new_file = page_dir / f"v{new_version}.html"
    atomic_write_text(new_file, body)
    if draft.parent == page_dir:
        try:
            draft.unlink()
        except OSError:
            pass

    meta.update({
        "latest_remote_version": new_version,
        "latest_local_file": new_file.name,
        "fetched_at": now_iso(),
        "fetched_by_agent": get_agent_id(),
        "title": title,
    })
    write_meta(page_dir, meta)
    append_push_log(page_dir, f"PUSH v{cached_ver}->v{new_version} agent={get_agent_id()} size={len(body)}")

    print(f"OK pushed v{new_version} ({len(body)} chars)", file=sys.stderr)
    return 0


# ====== Subcommand: diff ======


def cmd_diff(args: argparse.Namespace) -> int:
    cache_root = get_cache_root(args.cache_dir)
    page_dir = cache_root / "confluence" / args.page_id
    if not page_dir.exists():
        raise SystemExit(f"No cache for page {args.page_id}. Run 'pull' first.")

    meta = read_meta(page_dir)
    cached_ver = meta.get("latest_remote_version")
    if not cached_ver:
        raise SystemExit("Cache meta missing latest_remote_version.")

    base = page_dir / f"v{cached_ver}.html"
    draft = page_dir / f"v{cached_ver}.draft.html"

    if not base.exists():
        raise SystemExit(f"Base file missing: {base}")
    if not draft.exists():
        print(f"No draft to diff (no changes since pull).")
        return 0

    base_lines = base.read_text(encoding="utf-8").splitlines(keepends=True)
    draft_lines = draft.read_text(encoding="utf-8").splitlines(keepends=True)

    diff = list(difflib.unified_diff(
        base_lines, draft_lines,
        fromfile=f"v{cached_ver}.html (cached remote)",
        tofile=f"v{cached_ver}.draft.html (your edits)",
        n=3,
    ))
    if not diff:
        print(f"No changes between v{cached_ver}.html and draft.")
        return 0
    sys.stdout.writelines(diff)
    return 0


# ====== Subcommand: cache-status ======


def cmd_cache_status(args: argparse.Namespace) -> int:
    cache_root = get_cache_root(args.cache_dir)
    conf_root = cache_root / "confluence"
    if not conf_root.exists():
        print(f"No cache at {conf_root}")
        return 0

    pages = sorted([p for p in conf_root.iterdir() if p.is_dir()])
    if args.page_id:
        pages = [p for p in pages if p.name == args.page_id]

    if not pages:
        print("(empty)")
        return 0

    print(f"{'PAGE-ID':<15} {'VERSION':<8} {'TITLE':<40} {'DRAFT':<8} {'FETCHED-AT':<22} {'BY':<10}")
    print("-" * 110)
    for page_dir in pages:
        meta = read_meta(page_dir)
        ver = meta.get("latest_remote_version", "?")
        title = (meta.get("title") or "?")[:38]
        fetched = meta.get("fetched_at", "?")[:22]
        agent = meta.get("fetched_by_agent", "?")[:10]
        draft = "Yes" if (page_dir / f"v{ver}.draft.html").exists() else "-"
        print(f"{page_dir.name:<15} v{ver:<7} {title:<40} {draft:<8} {fetched:<22} {agent:<10}")

        # List local versions
        versions = sorted([
            int(re.match(r"v(\d+)\.html$", f.name).group(1))
            for f in page_dir.glob("v*.html")
            if re.match(r"v\d+\.html$", f.name)
        ])
        if versions:
            print(f"  versions: {versions}")
    return 0


# ====== Subcommand: clear-cache ======


def cmd_clear_cache(args: argparse.Namespace) -> int:
    cache_root = get_cache_root(args.cache_dir)
    conf_root = cache_root / "confluence"
    if not conf_root.exists():
        print("Nothing to clear.")
        return 0

    if args.page_id:
        page_dir = conf_root / args.page_id
        if not page_dir.exists():
            print(f"No cache for {args.page_id}")
            return 0
        # Preserve push.log
        log = page_dir / "push.log"
        log_content = log.read_text(encoding="utf-8") if log.exists() else None
        shutil.rmtree(page_dir)
        if log_content:
            page_dir.mkdir()
            log.write_text(log_content, encoding="utf-8")
        print(f"Cleared cache for {args.page_id} (push.log preserved)")
    else:
        if not args.yes:
            print(f"Refusing to clear ALL cached pages without --yes")
            return 1
        for p in conf_root.iterdir():
            if p.is_dir():
                shutil.rmtree(p)
        print(f"Cleared all cache under {conf_root}")
    return 0


# ====== Subcommand: get-page (read-only, doesn't touch cache) ======


def cmd_get_page(args: argparse.Namespace) -> int:
    fmt = args.format
    if fmt == "storage":
        expand = "body.storage,version,space,title"
    elif fmt == "view":
        # body.view = Confluence-rendered HTML (final display HTML)
        expand = "body.view,version,space,title"
    else:
        raise SystemExit(f"unknown format: {fmt}")

    data = call_api_json("confluence", f"rest/api/content/{args.page_id}?expand={expand}")
    if not data:
        raise SystemExit("Empty response")

    if args.json:
        print(json.dumps(data, ensure_ascii=False, indent=2))
        return 0

    body_key = "storage" if fmt == "storage" else "view"
    body = (data.get("body", {}).get(body_key, {}) or {}).get("value", "")
    print(f"# {data.get('title', '?')} (v{data.get('version', {}).get('number')})", file=sys.stderr)
    print(f"# space={data.get('space', {}).get('key', '?')}  format={fmt}", file=sys.stderr)
    print(body)
    return 0


# ====== Subcommand: create-page ======


def cmd_create_page(args: argparse.Namespace) -> int:
    body = Path(args.file).read_text(encoding="utf-8")
    payload: dict[str, Any] = {
        "type": "page",
        "title": args.title,
        "space": {"key": args.space},
        "body": {"storage": {"value": body, "representation": "storage"}},
    }
    if args.parent:
        payload["ancestors"] = [{"id": args.parent}]

    tmp = tempfile.NamedTemporaryFile(suffix=".json", mode="w", encoding="utf-8", delete=False)
    try:
        json.dump(payload, tmp, ensure_ascii=False)
        tmp.close()
        rc, stdout, stderr = call_api(
            "confluence", "rest/api/content", method="POST", body_file=tmp.name,
        )
        if rc != 0:
            print(f"ERROR: {stderr}\n{stdout}", file=sys.stderr)
            return 1
    finally:
        os.unlink(tmp.name)

    text = stdout.strip()
    if text.startswith("﻿"):
        text = text[1:]
    data = json.loads(text)
    print(f"OK created page id={data.get('id')} title='{data.get('title')}'")
    return 0


# ====== Subcommand: search (CQL) ======


def cmd_search(args: argparse.Namespace) -> int:
    from urllib.parse import quote
    cql = args.cql
    path = f"rest/api/content/search?cql={quote(cql)}&limit={args.limit}&expand=version,space"
    data = call_api_json("confluence", path)
    results = data.get("results", []) if data else []
    if args.json:
        print(json.dumps(data, ensure_ascii=False, indent=2))
        return 0
    print(f"{'PAGE-ID':<15} {'SPACE':<15} {'TYPE':<8} {'VER':<5} TITLE")
    print("-" * 80)
    for r in results:
        print(f"{r.get('id', '?'):<15} {r.get('space', {}).get('key', '?'):<15} "
              f"{r.get('type', '?'):<8} v{r.get('version', {}).get('number', '?'):<4} "
              f"{r.get('title', '?')}")
    print(f"\nTotal: {len(results)} (size={data.get('size')}, limit={args.limit})")
    return 0


# ====== Subcommand: get-page-children ======


def cmd_get_page_children(args: argparse.Namespace) -> int:
    data = call_api_json(
        "confluence",
        f"rest/api/content/{args.page_id}/child/page?limit={args.limit}&expand=version",
    )
    results = data.get("results", []) if data else []
    if args.json:
        print(json.dumps(data, ensure_ascii=False, indent=2))
        return 0
    for r in results:
        print(f"{r.get('id', '?'):<15} v{r.get('version', {}).get('number', '?'):<5} {r.get('title', '?')}")
    print(f"\nTotal: {len(results)}")
    return 0


# ====== Subcommand: get-page-history ======


def cmd_get_page_history(args: argparse.Namespace) -> int:
    data = call_api_json(
        "confluence",
        f"rest/api/content/{args.page_id}/version?limit={args.limit}",
    )
    results = data.get("results", []) if data else []
    if args.json:
        print(json.dumps(data, ensure_ascii=False, indent=2))
        return 0
    print(f"{'VER':<5} {'WHEN':<22} {'WHO':<20} {'MSG':<50}")
    print("-" * 100)
    for r in results:
        by = r.get("by", {})
        username = by.get("username") or by.get("displayName", "?")
        print(f"v{r.get('number', '?'):<4} {r.get('when', '?')[:22]:<22} {username:<20} {(r.get('message') or '')[:50]}")
    return 0


# ====== Subcommand: get-page-diff (between two remote versions) ======


def cmd_get_page_diff(args: argparse.Namespace) -> int:
    """Fetch v_from and v_to body.storage and unified-diff them."""
    def fetch_version(v):
        return call_api_json(
            "confluence",
            f"rest/api/content/{args.page_id}?expand=body.storage,version&version={v}",
        )

    a = fetch_version(args.from_version)
    b = fetch_version(args.to_version)
    a_body = (a.get("body", {}).get("storage", {}) or {}).get("value", "").splitlines(keepends=True)
    b_body = (b.get("body", {}).get("storage", {}) or {}).get("value", "").splitlines(keepends=True)
    diff = list(difflib.unified_diff(
        a_body, b_body,
        fromfile=f"v{args.from_version}",
        tofile=f"v{args.to_version}",
    ))
    if not diff:
        print(f"No changes between v{args.from_version} and v{args.to_version}")
        return 0
    sys.stdout.writelines(diff)
    return 0


# ====== Subcommand: get-comments ======


def cmd_get_comments(args: argparse.Namespace) -> int:
    data = call_api_json(
        "confluence",
        f"rest/api/content/{args.page_id}/child/comment?expand=body.view,version&limit={args.limit}",
    )
    results = data.get("results", []) if data else []
    if args.json:
        print(json.dumps(data, ensure_ascii=False, indent=2))
        return 0
    for r in results:
        ver = r.get("version", {})
        body = (r.get("body", {}).get("view", {}) or {}).get("value", "")
        # strip HTML tags for terminal display
        text = re.sub(r"<[^>]+>", "", body).strip()
        print(f"--- comment id={r.get('id')} by {ver.get('by',{}).get('displayName','?')} at {ver.get('when','?')[:19]} ---")
        print(text[:500])
        print()
    print(f"Total: {len(results)}")
    return 0


# ====== Subcommand: add-comment ======


def cmd_add_comment(args: argparse.Namespace) -> int:
    if args.file:
        body_html = Path(args.file).read_text(encoding="utf-8")
    elif args.text:
        # Wrap plain text in storage <p>
        body_html = f"<p>{_html_escape(args.text)}</p>"
    else:
        raise SystemExit("provide --text or --file")

    payload = {
        "type": "comment",
        "container": {"id": args.page_id, "type": "page"},
        "body": {"storage": {"value": body_html, "representation": "storage"}},
    }
    tmp = tempfile.NamedTemporaryFile(suffix=".json", mode="w", encoding="utf-8", delete=False)
    try:
        json.dump(payload, tmp, ensure_ascii=False)
        tmp.close()
        rc, stdout, stderr = call_api("confluence", "rest/api/content", method="POST", body_file=tmp.name)
        if rc != 0:
            print(f"ERROR: {stderr}\n{stdout}", file=sys.stderr)
            return 1
    finally:
        os.unlink(tmp.name)
    text = stdout.strip()
    if text.startswith("﻿"):
        text = text[1:]
    data = json.loads(text)
    print(f"OK comment id={data.get('id')} added to page {args.page_id}")
    return 0


def _html_escape(s: str) -> str:
    return (s.replace("&", "&amp;")
             .replace("<", "&lt;")
             .replace(">", "&gt;"))


# ====== Subcommand: delete-page ======


def cmd_delete_page(args: argparse.Namespace) -> int:
    if not args.yes:
        print(f"Refusing to delete page {args.page_id} without --yes", file=sys.stderr)
        return 1
    rc, stdout, stderr = call_api("confluence", f"rest/api/content/{args.page_id}", method="DELETE")
    if rc != 0:
        print(f"ERROR: {stderr}\n{stdout}", file=sys.stderr)
        return 1
    print(f"OK deleted page {args.page_id}")
    return 0


# ====== Subcommand: move-page ======


def cmd_move_page(args: argparse.Namespace) -> int:
    # Fetch current to preserve title/version AND body.
    # Confluence PUT replaces the entire page representation; if `body` is omitted,
    # some server versions return 400, others silently wipe content. Always include
    # body.storage to be safe.
    cur = call_api_json(
        "confluence",
        f"rest/api/content/{args.page_id}?expand=version,title,space,body.storage",
    )
    body_value = ((cur.get("body") or {}).get("storage") or {}).get("value", "")
    payload = {
        "version": {"number": cur["version"]["number"] + 1},
        "title": cur["title"],
        "type": "page",
        "ancestors": [{"id": args.parent}],
        "body": {"storage": {"value": body_value, "representation": "storage"}},
    }
    tmp = tempfile.NamedTemporaryFile(suffix=".json", mode="w", encoding="utf-8", delete=False)
    try:
        json.dump(payload, tmp, ensure_ascii=False)
        tmp.close()
        rc, stdout, stderr = call_api(
            "confluence", f"rest/api/content/{args.page_id}",
            method="PUT", body_file=tmp.name,
        )
        if rc != 0:
            print(f"ERROR: {stderr}\n{stdout}", file=sys.stderr)
            return 1
    finally:
        os.unlink(tmp.name)
    print(f"OK moved page {args.page_id} under parent {args.parent}")
    return 0


# ====== Subcommand: upload-attachment ======


def cmd_upload_attachment(args: argparse.Namespace) -> int:
    src = Path(args.file).resolve()
    if not src.exists():
        raise SystemExit(f"File not found: {src}")
    # Confluence requires multipart upload with X-Atlassian-Token: no-check
    # Easiest via curl directly (atl-query.ps1 is JSON-oriented).
    # We invoke curl with --netrc here.
    config = _read_config()
    base = config.get("CONFLUENCE_URL", "")
    if not base:
        raise SystemExit("CONFLUENCE_URL not configured")
    url = f"{base.rstrip('/')}/rest/api/content/{args.page_id}/child/attachment"

    cmd = [
        "curl", "-s", "--netrc",
        "-H", "X-Atlassian-Token: no-check",
        "-F", f"file=@{src};filename={src.name}",
        "-X", "POST", url,
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True, encoding="utf-8", errors="replace")
    if proc.returncode != 0:
        print(f"ERROR: {proc.stderr}\n{proc.stdout}", file=sys.stderr)
        return 1
    print(proc.stdout)
    return 0


# ====== Subcommand: download-attachment ======


def cmd_download_attachment(args: argparse.Namespace) -> int:
    # List attachments to find the matching one
    data = call_api_json(
        "confluence",
        f"rest/api/content/{args.page_id}/child/attachment?expand=version&limit=200",
    )
    target = None
    for r in (data or {}).get("results", []):
        if r.get("title") == args.filename:
            target = r
            break
    if not target:
        print(f"No attachment named '{args.filename}' on page {args.page_id}", file=sys.stderr)
        return 1

    download_link = target.get("_links", {}).get("download", "")
    if not download_link:
        # Fallback: build from id
        download_link = f"/download/attachments/{args.page_id}/{args.filename}"

    config = _read_config()
    base = config.get("CONFLUENCE_URL", "")
    url = f"{base.rstrip('/')}{download_link}"

    out = Path(args.out) if args.out else Path(args.filename)
    # Run curl in binary mode (no text decoding) to handle non-ASCII filenames safely.
    # curl writes the binary body directly via -o; we only need exit code + stderr.
    # Decode stderr explicitly as UTF-8 with error replacement to avoid cp936 surprises.
    cmd = ["curl", "-s", "-S", "--netrc", "-L", "-o", str(out), "-w", "%{http_code}", url]
    proc = subprocess.run(cmd, capture_output=True)  # bytes, not text
    if proc.returncode != 0:
        err = proc.stderr.decode("utf-8", errors="replace")
        print(f"ERROR curl exit {proc.returncode}: {err}", file=sys.stderr)
        return 1
    http_code = proc.stdout.decode("ascii", errors="replace").strip()
    if http_code.startswith(("4", "5")):
        # curl wrote (likely error JSON) into the output file; read first 500 bytes for diagnosis
        snippet = ""
        if out.exists():
            try:
                snippet = out.read_bytes()[:500].decode("utf-8", errors="replace")
            except Exception:
                pass
        print(f"ERROR HTTP {http_code} downloading '{args.filename}'. Response snippet: {snippet}",
              file=sys.stderr)
        return 1
    size = out.stat().st_size if out.exists() else 0
    print(f"OK downloaded -> {out} ({size} bytes)")
    return 0


def _read_config() -> dict:
    cfg = Path.home() / ".claude" / "skill-config" / "atlassian" / "config.env"
    out: dict[str, str] = {}
    if not cfg.exists():
        return out
    for line in cfg.read_text(encoding="utf-8", errors="replace").splitlines():
        m = re.match(r"^([A-Z_]+)=(.+)$", line.strip())
        if m:
            out[m.group(1)] = m.group(2).strip()
    return out


# ====== argparse ======


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="atl-confluence: Confluence CLI with cache + version-aware push")
    p.add_argument("--cache-dir", help="Override cache root (default: <cwd>/.atlassian-cache)")
    sub = p.add_subparsers(dest="cmd", required=True)

    sp = sub.add_parser("pull", help="fetch page to cache")
    sp.add_argument("page_id")
    sp.add_argument("--version", type=int, help="fetch specific version (default: latest)")
    sp.add_argument("--force", action="store_true", help="overwrite local file even if cached")
    sp.set_defaults(func=cmd_pull)

    sp = sub.add_parser("push", help="push draft to remote (version+1)")
    sp.add_argument("page_id")
    sp.add_argument("--draft", help="path to draft file (default: cache/v<N>.draft.html)")
    sp.add_argument("--force", action="store_true", help="push even if remote moved")
    sp.set_defaults(func=cmd_push)

    sp = sub.add_parser("diff", help="diff cached remote vs draft")
    sp.add_argument("page_id")
    sp.set_defaults(func=cmd_diff)

    sp = sub.add_parser("cache-status", help="list cached pages")
    sp.add_argument("--page-id", help="show only this page")
    sp.set_defaults(func=cmd_cache_status)

    sp = sub.add_parser("clear-cache", help="clear cached page(s)")
    sp.add_argument("--page-id", help="clear only this page; omit + --yes for all")
    sp.add_argument("--yes", action="store_true", help="confirm clearing all")
    sp.set_defaults(func=cmd_clear_cache)

    sp = sub.add_parser("get-page", help="read page (no cache)")
    sp.add_argument("page_id")
    sp.add_argument("--format", choices=("storage", "view"), default="storage",
                    help="storage = raw XHTML (preserves macros); view = Confluence-rendered HTML")
    sp.add_argument("--json", action="store_true", help="print full JSON instead of body")
    sp.set_defaults(func=cmd_get_page)

    sp = sub.add_parser("create-page", help="create new page from HTML file")
    sp.add_argument("--space", required=True, help="space key")
    sp.add_argument("--title", required=True)
    sp.add_argument("--parent", help="parent page id (optional)")
    sp.add_argument("--file", required=True, help="storage XHTML file")
    sp.set_defaults(func=cmd_create_page)

    sp = sub.add_parser("search", help="CQL search")
    sp.add_argument("--cql", required=True, help="CQL expression")
    sp.add_argument("--limit", type=int, default=25)
    sp.add_argument("--json", action="store_true")
    sp.set_defaults(func=cmd_search)

    sp = sub.add_parser("get-page-children", help="list child pages")
    sp.add_argument("page_id")
    sp.add_argument("--limit", type=int, default=200)
    sp.add_argument("--json", action="store_true")
    sp.set_defaults(func=cmd_get_page_children)

    sp = sub.add_parser("get-page-history", help="version history")
    sp.add_argument("page_id")
    sp.add_argument("--limit", type=int, default=50)
    sp.add_argument("--json", action="store_true")
    sp.set_defaults(func=cmd_get_page_history)

    sp = sub.add_parser("get-page-diff", help="diff two remote versions")
    sp.add_argument("page_id")
    sp.add_argument("--from", dest="from_version", type=int, required=True)
    sp.add_argument("--to", dest="to_version", type=int, required=True)
    sp.set_defaults(func=cmd_get_page_diff)

    sp = sub.add_parser("get-comments", help="list comments")
    sp.add_argument("page_id")
    sp.add_argument("--limit", type=int, default=50)
    sp.add_argument("--json", action="store_true")
    sp.set_defaults(func=cmd_get_comments)

    sp = sub.add_parser("add-comment", help="add comment")
    sp.add_argument("page_id")
    sp.add_argument("--text", help="plain text (auto-wrapped in <p>)")
    sp.add_argument("--file", help="storage XHTML file")
    sp.set_defaults(func=cmd_add_comment)

    sp = sub.add_parser("delete-page", help="delete page (requires --yes)")
    sp.add_argument("page_id")
    sp.add_argument("--yes", action="store_true")
    sp.set_defaults(func=cmd_delete_page)

    sp = sub.add_parser("move-page", help="move page under new parent")
    sp.add_argument("page_id")
    sp.add_argument("--parent", required=True, help="new parent page id")
    sp.set_defaults(func=cmd_move_page)

    sp = sub.add_parser("upload-attachment", help="upload file to page")
    sp.add_argument("page_id")
    sp.add_argument("--file", required=True)
    sp.set_defaults(func=cmd_upload_attachment)

    sp = sub.add_parser("download-attachment", help="download attachment by filename")
    sp.add_argument("page_id")
    sp.add_argument("--filename", required=True)
    sp.add_argument("--out", help="output path (default: ./<filename>)")
    sp.set_defaults(func=cmd_download_attachment)

    return p


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
